# Generated by Django 4.1.1 on 2022-09-19 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('httpserver', '0003_rename_name_image_filename_image_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
